variables:
  TARGET_DIR: /var/data/artifacts/$CI_PROJECT_NAME

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - maven
  script:
    - mvn clean package -Dmaven.javadoc.skip=true
  except:
    - master
  artifacts:
    paths:
      - platform/platform-bukkit/target/*.jar
      - platform/platform-bungee/target/*.jar

deploy:
  # 部署到 正式服文件夹
  stage: deploy
  tags:
    - maven
  script:
    - mvn clean deploy -DskipTests # 有API接口的情况下，部署到maven仓库。
    - mkdir -p $TARGET_DIR # 先移动到构建完成用于存储的文件夹
    - rm -rf $TARGET_DIR/*
    - cp -vrf ./*/target/*.jar $TARGET_DIR/
    - rm -vrf $TARGET_DIR/*-API* # 移除API文件
    - rm -vrf $TARGET_DIR/original* # 移除非必须文件
  only:
    - master # 只有在主分支提交时执行
  artifacts:
    paths:
      - platform/platform-bukkit/target/*.jar
      - platform/platform-bungee/target/*.jar